--- /dev/null
+++ b/Makefile
@@ -0,0 +1,3 @@
+default %:
+	make $@ -C doc
+	make $@ -C src
--- a/src/Makefile-dist
+++ b/src/Makefile-dist
@@ -485,7 +485,8 @@
 	a.out \
 	pfft3ds.f90 fft3dsp.f90 fft3dsp_subr.f90 fft3duz.f90 fft3duz_subr.f90 \
 	fftgrid.h mkl_dfti.f90 fftgrid-vx.h \
-	xticonv strconv diffstr iplstr cmpstr
+	xticonv strconv diffstr iplstr cmpstr \
+	dftd3/*.o
 
 ################## FOR ESM METHOD by M.Otani 2006/02/06####################
 ################## Modified by Y.Ando 2011/01/21 ##########################
@@ -507,6 +508,10 @@
 .F.f:
 	${CPP} -P ${DEFINES} $< | sed '/^ *$$/d' > $*.f
 
+install: default
+	install -d $(DESTDIR)/usr/bin
+	install inipot cgmrpt mdrpt vbpef vbstm wfn2chg wannier pefcos xticonv strconv diffstr iplstr cmpstr pe2dos tetrapdos hmatr2bnd $(DESTDIR)/usr/bin
+
 # Local Variables: ***
 # mode:Makefile ***
 # End:***
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -1,8 +1,10 @@
 default: develop.pdf example-c6h12.pdf example-cu.pdf formalism.pdf inputformat.pdf programs.pdf tutorial.pdf
 
-clean:
+clean distclean:
 	rm -f *.aux *.dvi *.log *.toc *.pdf
 
+install:
+
 develop.pdf:
 	platex --kanji=euc develop.tex
 	platex --kanji=euc develop.tex
@@ -19,8 +21,8 @@
 	dvipdfmx -o example-cu.pdf example-cu.dvi
 
 formalism.pdf:
-	platex --kanji=sjis formalism.tex
-	platex --kanji=sjis formalism.tex
+	platex --kanji=euc formalism.tex
+	platex --kanji=euc formalism.tex
 	dvipdfmx -o formalism.pdf formalism.dvi
 
 inputformat.pdf:
