--- /dev/null
+++ b/Makefile
@@ -0,0 +1,3 @@
+default %:
+	make $@ -C doc
+	make $@ -C src
--- a/src/Makefile-dist
+++ b/src/Makefile-dist
@@ -488,7 +488,8 @@
 	a.out \
 	pfft3ds.f90 fft3dsp.f90 fft3dsp_subr.f90 fft3duz.f90 fft3duz_subr.f90 \
 	fftgrid.h mkl_dfti.f90 fftgrid-vx.h \
-	xticonv strconv diffstr iplstr cmpstr
+	xticonv strconv diffstr iplstr cmpstr \
+	dftd3/*.o
 
 ################## FOR ESM METHOD by M.Otani 2006/02/06####################
 ################## Modified by Y.Ando 2011/01/21 ##########################
@@ -510,6 +511,10 @@
 .F.f:
 	${CPP} -P ${DEFINES} $< | sed '/^ *$$/d' > $*.f
 
+install: default
+	install -d $(DESTDIR)/usr/bin
+	install inipot cgmrpt mdrpt vbpef vbstm wfn2chg wannier pefcos xticonv strconv diffstr iplstr cmpstr pe2dos tetrapdos hmatr2bnd $(DESTDIR)/usr/bin
+
 # Local Variables: ***
 # mode:Makefile ***
 # End:***
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -1,8 +1,10 @@
 default: develop.pdf example-c6h12.pdf example-cu.pdf formalism.pdf inputformat.pdf programs.pdf tutorial.pdf
 
-clean:
+clean distclean:
 	rm -f *.aux *.dvi *.log *.toc *.pdf
 
+install:
+
 develop.pdf:
 	platex --kanji=euc develop.tex
 	platex --kanji=euc develop.tex
@@ -19,8 +21,8 @@
 	dvipdfmx -o example-cu.pdf example-cu.dvi
 
 formalism.pdf:
-	platex --kanji=sjis formalism.tex
-	platex --kanji=sjis formalism.tex
+	platex --kanji=euc formalism.tex
+	platex --kanji=euc formalism.tex
 	dvipdfmx -o formalism.pdf formalism.dvi
 
 inputformat.pdf:
--- a/src/vbchrg.f90
+++ b/src/vbchrg.f90
@@ -834,7 +834,7 @@
 
        call rg2tsu2(rg(:,:,jrg),aa,tsu2)
        psum = (0.0d0,0.0d0)
-       if (srg(irdkpt%irrg(irg))) then
+       if (srg(irdkpt%irrg(irg)).eq.1) then
           do ib=1,nw
              do jb=1,wan_n_occ
                 do ig=bkm,ekm
--- a/src/wannier.F90
+++ b/src/wannier.F90
@@ -227,9 +227,9 @@
      call MPI_FINALIZE(ierr)
      stop
   end if
-  if ( mod(nk,mmm(1,2,1).ne.0) .or. &
-       mod(nk,mmm(2,2,1).ne.0) .or. &
-       mod(nk,mmm(3,2,1).ne.0) ) then
+  if ( mod(nk,mmm(1,2,1)).ne.0 .or. &
+       mod(nk,mmm(2,2,1)).ne.0 .or. &
+       mod(nk,mmm(3,2,1)).ne.0 ) then
      write(6,*) 'mod( bz_mesh, mmm(1:3,2,1) ) must be 0 for wannier'
      call MPI_FINALIZE(ierr)
      stop
